

export enum Role{
    USER='USER',
    ARTISTA='ARTISTA',
    ORGANIZADOR='ORGANIZADOR',
    ADMIN='ADMIN'
}

export enum TipoBoleto{
    VIP='VIP',
    GENERAL='GENERAL',
    PLATINO='PLATINO',
    ORO='ORO'
}
export enum EstadoOrden{
    PENDIENTE='PENDIENTE',
    PAGADO='PAGADO',
    CANCELADO='CANCELADO',
    REEMBOLSADO='REEMBOLSADO'
}

export enum RolArtista{
    HEADLINER='HEADLINER',
    TELONERO='TELONERO',
    INVITADO='INVITADO',
    COLABORADOR='COLABORADOR'
}